# Generated by Django 5.0.3 on 2024-03-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_employee_salaryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salaryId',
            new_name='salary_id',
        ),
    ]
